#!/usr/bin/env bash

#
# Copyright (C) 2022 Mahmoud Mohamed (Ozil)  <https://github.com/mmsaeed509>
# LICENSE © GNU-GPL3
#

# Environtment path
export PATH="${PATH}:$HOME/.config/bspwm/bin"

# Get colors from .Xresources 
xrdb ~/.Xresources
getcolors() {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
getcolors

# ------------ Configurations ------------ #

# -------------------- set En & Ar for keyboard --------------------
setxkbmap -layout us -variant intl

# Solve java apps issues (e.g. JetBrains IDEs like PyCharm, CLion, etc).
export _JAVA_AWT_WM_NONREPARENTING=1 


# ------------ Dual monitor setup ------------
#
# run xrandr -q | grep " connected" | cut -d ' ' -f1   to list monitors
# in my case eDP1 , HDMI-1-0
# change 'HDMI-1-0' to your output
 
# if [[ $(xrandr -q | grep 'HDMI-1-0 connected') ]]; then

# 		  # use arandr or xrandr to set monitors config
# 		  # in my case, i use laptop monitor (eDP1) as Primary display 
# 		  # and the second monitor (HDMI-1-0) as external display (extended to right)
# 		  # add your config to this directory  ~/.screenlayout/   ||  If it doesn't exist, create one
# 		  bash ~/.screenlayout/mainLeftExRight.sh
# fi

# ------------ Dual monitor setup ------------

# ------------ workspaces config ------------
workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		bspc monitor ${monitor} -n "$name" -d 0 1 2 3 4 5 6 7 8 9
		let name++
	done
}

workspaces

bspc config border_width 2
bspc config window_gap 10
bspc config split_ratio 0.50

bspc config focused_border_color "$BLUE" 
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

# ------------ workspaces config ------------


# ------------ Window rules ------------

# remove all rules first
# bspc rule -r *:*

bspc rule -a Emacs state=tiled
# ------------ Autostart

# Kill if already running
killall -9 sxhkd dunst

# Lauch notification daemon
dunst \
-geom "280x50-10+42" -frame_width "1" -font "Iosevka Custom 9" \
-lb "$BACKGROUND" -lf "$FOREGROUND" -lfr "$BLUE" \
-nb "$BACKGROUND" -nf "$FOREGROUND" -nfr "$BLUE" \
-cb "$BACKGROUND" -cf "$RED" -cfr "$RED" &

# Lauch keybindings daemon
sxhkd &

# Fix cursor
xsetroot -cursor_name left_ptr

# Start mpd
exec mpd &

# Start bspwm scripts
bspcolors
bspcomp
bspbar
bspfloat &

feh --bg-fill $HOME/wallpapers/ultrawide/hyperbeast/human_face_cropped.jpg

picom &
